name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js version 16
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: installing package on first challenge
        working-directory: ./first_challenge
        run: npm install

      - name: running test on first challenge
        working-directory: ./first_challenge
        run: npm run test

      - name: installing package on second challenge
        working-directory: ./second_challenge
        run: npm install

      - name: running test on second challenge
        working-directory: ./second_challenge
        run: npm run test
