name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: 16.x

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js version 16
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: installing package
        working-directory: ./first_challenge
        run: npm install

      - name: running test
        working-directory: ./first_challenge
        run: npm run test
